### ISSUE TITLE
error on running meteor run

### ISSUE THREAD

**Issue by xiaopow** [boxxa/meteor-polymer-elements#1]
```
  baz  meteor run
[[[[[ /private/tmp/baz ]]]]]

=> Started proxy.
=> Started MongoDB.
I20150602-16:18:37.160(8)? Polymer exist already. To reinitialize, remove bower_components from your public/ folder
I20150602-16:18:37.641(8)? installing polymer-elements
W20150602-16:18:38.295(8)? (STDERR)
W20150602-16:18:38.295(8)? (STDERR) /Users/XiaoAir/.meteor/packages/meteor-tool/.1.1.3.1wysac9++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/server-lib/node_modules/fibers/future.js:278
W20150602-16:18:38.296(8)? (STDERR)                         throw(ex);
W20150602-16:18:38.296(8)? (STDERR)                               ^
W20150602-16:18:38.310(8)? (STDERR) Error: No tag found that was able to satisfy 1.0.0
W20150602-16:18:38.310(8)? (STDERR)     at Object.Future.wait (/Users/XiaoAir/.meteor/packages/meteor-tool/.1.1.3.1wysac9++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/server-lib/node_modules/fibers/future.js:398:15)
W20150602-16:18:38.310(8)? (STDERR)     at Object.install (packages/meteor/helpers.js:119:1)
W20150602-16:18:38.310(8)? (STDERR)     at Package (packages/boxxa:polymer-elements/boxxa:polymer-elements.js:25:1)
W20150602-16:18:38.310(8)? (STDERR)     at /private/tmp/baz/.meteor/local/build/programs/server/packages/boxxa_polymer-elements.js:50:4
W20150602-16:18:38.310(8)? (STDERR)     at /private/tmp/baz/.meteor/local/build/programs/server/packages/boxxa_polymer-elements.js:57:3
W20150602-16:18:38.310(8)? (STDERR)     at /private/tmp/baz/.meteor/local/build/programs/server/boot.js:222:10
W20150602-16:18:38.310(8)? (STDERR)     at Array.forEach (native)
W20150602-16:18:38.310(8)? (STDERR)     at Function._.each._.forEach (/Users/XiaoAir/.meteor/packages/meteor-tool/.1.1.3.1wysac9++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/server-lib/node_modules/underscore/underscore.js:79:11)
W20150602-16:18:38.311(8)? (STDERR)     at /private/tmp/baz/.meteor/local/build/programs/server/boot.js:117:5
W20150602-16:18:38.311(8)? (STDERR)     - - - - -
W20150602-16:18:38.311(8)? (STDERR)     at createError (/Users/XiaoAir/.meteor/packages/boxxa_polymer-elements/.1.0.0.sf5kqf++os+web.browser+web.cordova/npm/node_modules/bower/lib/util/createError.js:4:15)
W20150602-16:18:38.311(8)? (STDERR)     at /Users/XiaoAir/.meteor/packages/boxxa_polymer-elements/.1.0.0.sf5kqf++os+web.browser+web.cordova/npm/node_modules/bower/lib/core/resolvers/GitResolver.js:144:23
W20150602-16:18:38.311(8)? (STDERR)     at /Users/XiaoAir/.meteor/packages/boxxa_polymer-elements/.1.0.0.sf5kqf++os+web.browser+web.cordova/npm/node_modules/bower/node_modules/q/q.js:1142:26
W20150602-16:18:38.311(8)? (STDERR)     at _fulfilled (/Users/XiaoAir/.meteor/packages/boxxa_polymer-elements/.1.0.0.sf5kqf++os+web.browser+web.cordova/npm/node_modules/bower/node_modules/q/q.js:787:54)
W20150602-16:18:38.311(8)? (STDERR)     at self.promiseDispatch.done (/Users/XiaoAir/.meteor/packages/boxxa_polymer-elements/.1.0.0.sf5kqf++os+web.browser+web.cordova/npm/node_modules/bower/node_modules/q/q.js:816:30)
W20150602-16:18:38.311(8)? (STDERR)     at Promise.promise.promiseDispatch (/Users/XiaoAir/.meteor/packages/boxxa_polymer-elements/.1.0.0.sf5kqf++os+web.browser+web.cordova/npm/node_modules/bower/node_modules/q/q.js:749:13)
W20150602-16:18:38.311(8)? (STDERR)     at /Users/XiaoAir/.meteor/packages/boxxa_polymer-elements/.1.0.0.sf5kqf++os+web.browser+web.cordova/npm/node_modules/bower/node_modules/q/q.js:509:49
W20150602-16:18:38.311(8)? (STDERR)     at flush (/Users/XiaoAir/.meteor/packages/boxxa_polymer-elements/.1.0.0.sf5kqf++os+web.browser+web.cordova/npm/node_modules/bower/node_modules/q/q.js:108:17)
W20150602-16:18:38.311(8)? (STDERR)     at process._tickCallback (node.js:442:13)
=> Exited with code: 8
I20150602-16:18:40.456(8)? Polymer exist already. To reinitialize, remove bower_components from your public/ folder
I20150602-16:18:41.012(8)? installing polymer-elements
^C
```

**Comment by f3r** [comment]
+1

**Comment by boxxa** [comment]
I see the issue. I am not on a production laptop but will try to get the code pushed ASAP.

**Comment by boxxa** [comment]
Github is updated. Trying to figure out how to override Atmosphere's version.

**Comment by boxxa** [comment]
With the new polymer elements, this package is going to stop at 0.5.5 and be migrated to include each of the specific packages.

**Comment by boxxa** [comment]
New package created. Use: https://atmospherejs.com/boxxa/polymer-paper

**Comment by xiaopow** [comment]
Hi Boxxa, thanks for the quick fix. So are you saying this package is still using polymer 0.5.5?

**Comment by xiaopow** [comment]
Hi boxxa, can you please tell me how to install other elements? I understand you have made the new package install paper elements only. Thank you for the quick fix btw!!!! Kudos.

**Comment by boxxa** [comment]
Install the boxxa:polymer-paper which installs the base paper and iron elements. From there you can also git clone or copy your other elements you want to use into your public/bower_components folder. This being a package, I am trying to keep it as basic as possible so its usable and customizable and not too bloated. 

I have been looking at the new prebuilt elements and looking for ways to break them further into packages for people as well.
